test: provide test for error TS2305: Module '"../models/user"' has no exported member 'User'
An existence test is provided for the symbol given that is required by another module of the app