provide test for error error TS1345: An expression of type 'void' cannot be tested for truthiness
now that we have a test that use the UserModel.getByEmail static method we no longer need the existence test